version: "3.9"  # optional since v1.27.0
services:
    web:
        image: nginx
        ports:
            - "80:80"
            - "8080:8080"
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
    db:
        image: postgres 
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    backend:
        depends_on:
            - db
        ports:
            - "8000:8000"
        env_file:
            - ./backend/app/app/.env
        build:
            context: ./backend/app
            dockerfile: ./Dockerfile
